### ISSUE TITLE
Add support for Native Function serialization 

### ISSUE THREAD

**Issue by jeffRTC** [brokensandals/object-graph-as-json#7]
This should be easy one. I believe when you go over the functions, you can use a regex to check if it's a native function like below,

```
function isNativeFunction(f) {
       return !!f && (typeof f).toLowerCase() == 'function' 
       && (f === Function.prototype 
       || /^\s*function\s*(\b[a-z$_][a-z0-9$_]*\b)*\s*\((|([a-z$_][a-z0-9$_]*)(\s*,[a-z$_][a-z0-9$_]*)*)\)\s*{\s*\[native code\]\s*}\s*$/i.test(String(f)));
}
```

If it's native then I believe you can use a reference mechsmisim to serialize the native function. 

Right now, this lib serialize them using `toString `function which leaves the function as below,

`source: "function get usages() { [native code] }"
`

Let me know your thoughts on this!

**Comment by brokensandals** [comment]
Thanks for the suggested regex! Can you clarify what you mean by "use a reference mechanism"?

The file [builtins.js](https://github.com/brokensandals/object-graph-as-json/blob/master/src/builtins.js) contains a list of native functions (and other objects) that can be expected to exist in every javascript environment. When the encoder encounters those, it just records the name specified in that file, rather than serializing the object; the decoder can then look up the object using the name. If the native functions you're interested in are part of the javascript standard, they probably just need to be added to that file.

**Comment by jeffRTC** [comment]
The decoder actually fails because of that string I shown you so I made this issue because of that reason.

I was thinking something along line with `instanceof`

You lookup the `instanceof` the object and find if it's a native built in object. You can then use the matched native object's  Object.Prototype.NativeFunctionNameGoesHere as a reference it's function. 

```
let stringObject = new String();
stringObject instanceof String // True
```

One way to automatically check if it's a native built in object is to loop over the keys of window.

```
loop for keys in window,

if(stringObject instanceof window[key]) {
  // Do the work 
}
```

Suppose,

Encoder try to serialize this function,

`stringObject.charCodeAt`

It will end up as `"function fromCharCode() { [native code] }"`

Instead, I suggest to use the matched Native Object function as reference so 

`stringObject.charCodeAt` == `String.charCodeAt`  (Pardon me, I'm not sure this way is correct but just to highlight you the idea )

So,  The user will see string `"String.charCodeAt"` instead of `"function fromCharCode() { [native code] }"`

The decoder then take this raw string `"String.charCodeAt"` and look up the appropriate function  using dot notation and assign it to the decoded object

**Comment by brokensandals** [comment]
Interesting. The builtins.js file I mentioned above is intended to handle this sort of situation - it handles various native functions like `encodeURI`, `parseFloat`, etc. It doesn't need to check for the text `[native code]` because, before it even tries to serialize the function, it checks whether the function is in the known list of native functions.

But it uses an explicit list of native functions, which doesn't currently include any of the methods on String. If we added `String.charCodeAt` into that file, then it should be able to handle that one.

Of course, listing every method of every built-in type might be impractical. It might make sense to update that file so that for every type (like `String`), it loops over all the functions on the type, and adds them all to the list. Then, whenever the encoder encounters one of these functions, it will see that it's in that list and will serialize it with the standard name (like `String.charCodeAt`) instead of trying to serialize the function.

The reason to do it that way rather than looking for the text `[native code]` inside the string representation of the function, is that I'm not sure the string representation of the function gives us enough information to figure out where to find the function. For example, if I do:

```js
const foo = "whatever".charCodeAt;
new Encoder(foo)
```

the encoder ideally should be able to figure out that `foo` is `String.charCodeAt`, even though it doesn't know we got `foo` from a string object. Having the giant table of all native functions in `builtins.js` allows it to do that (as long as the table does actually include all native functions, which it currently doesn't).

**Comment by jeffRTC** [comment]
@brokensandals 

My idea mainly oriented towards to removing manual maintainece aka stopping cat and mouse game with browser vendors.

I suggest to add option for auto way along with keeping built in. So, the user can choose either built in types or automatic one. Maybe, automatic could be unsafe who knows..

**Comment by jeffRTC** [comment]
This one quite interesting. So, you brute force it to find out where it actually from. 

```
const foo = "whatever".charCodeAt;
new Encoder(foo)
```

Well, I do see the same with my automatic approach. It dump all native stuff in window object and go through each one. 

I will look if I can find for non-brute force way to automatically know where the method is actually from.

**Comment by jeffRTC** [comment]
Well, it seems there no way to know automatically where the method is actually from. Maybe there is some dark magic that I am not aware of..
